apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: weight-tracker-web-{{ git_branch }}
  name: weight-tracker-web
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/target: k8s.ruchij.com

spec:
  tls:
    - secretName: weight-tracker-web-tls
      hosts:
        - {{ git_branch }}.web.weight-tracker.ruchij.com
  rules:
    - host: {{ git_branch }}.web.weight-tracker.ruchij.com
      http:
        paths:
          - backend:
              serviceName: weight-tracker-web-service
              servicePort: 80
