---
- import_playbook: variables.yml

- hosts: localhost
  connection: local

  tasks:
    - copy:
        dest: ../build-info.json
        content: { "gitCommit": "{{ git_commit}}", "gitBranch": "{{ git_branch }}" }
