---
- import_playbook: variables.yml

- hosts: localhost
  connection: local

  tasks:
    - name: Delete existing "dist" directory
      file:
        path: dist
        state: absent

    - copy:
        dest: ../build-info.json
        content: |
          {
            "gitCommit": "{{ git_commit}}",
            "gitBranch": "{{ git_branch }}",
            "buildTimestamp": "{{ ansible_date_time.iso8601 }}"
          }

    - name: Fetch npm dependencies
      command: npm install

    - name: Build application
      command: npm run build

    - name: Build Docker image
      shell: |
        docker build \
          -t weight-tracker-web:{{ git_commit }} \
          -f ./docker/Dockerfile-prod \
          ../
