- import_playbook: variables.yml
- import_playbook: aws.yml

- hosts: localhost
  connection: local

  vars:
    k8s_config: "{{ lookup('aws_ssm', '/weight-tracker/k8s/config') }}"

  tasks:
    - name: Create K8s resource directory
      block:
        - name: Delete existing output directory
          file:
            path: output
            state: absent

        - name: Create output directory
          file:
            path: output
            state: directory

    - name: Create K8s config file
      copy:
        dest: output/kubeconfig
        content: "{{ k8s_config }}"

    - name: Render K8s resource files
      template:
        src: "{{ item }}"
        dest: "output/{{ item | basename }}"
      with_fileglob:
        - k8s/*.yaml
