---
- hosts: localhost
  connection: local

  tasks:
    - name: Set git branch name
      shell: git rev-parse --abbrev-ref HEAD | tr [:upper:] [:lower:] | tr " /" "-"
      register: git_branch_output

    - name: Set git commit
      command: git rev-parse --short HEAD
      register: git_commit_output

    - set_fact:
        git_branch: "{{ git_branch_output.stdout }}"
        git_commit: "{{ git_commit_output.stdout }}"
